export type FitnessContextSource = "v1" | "v2_1" | "v2_2";
export type FitnessContextErrorCode = "PROFILE_NOT_FOUND" | "READ_FAILED" | "V2_RECEIPT_INVALID" | "UNSUPPORTED_SCHEMA" | "V2_INCOMPLETE";

export class FitnessContextError extends Error {
  readonly code: FitnessContextErrorCode;
  readonly missingDomains: readonly string[];
  constructor(code: FitnessContextErrorCode, message: string, missingDomains: readonly string[] = []) {
    super(message); this.name = "FitnessContextError"; this.code = code; this.missingDomains = missingDomains;
  }
}

export type TrainingActivity = { activityCode: string; otherActivityLabel: string | null; scheduleType: string | null; availableWeekdays: number[] | null; sessionsPerWeek: number | null; durationRange: string | null; intensity: string | null };
export type NutritionRestriction = { restrictionType: string; restrictionCode: string | null; declaredLabel: string };
export type DeclaredFood = { foodCode: string | null; declaredLabel: string };
export type Supplement = { supplementCode: string | null; declaredLabel: string };

type FitnessContextShape = {
  source: FitnessContextSource; onboardingVersion: number | null; payloadSchemaVersion: 2 | 3 | null;
  identity: { name: string | null };
  health: { primaryGoal: string | null; birthDate: string | null; age: number | null; biologicalSex: string | null; heightCm: number | null; weightKg: number | null; targetWeightKg: number | null };
  training: { primaryGoal: string | null; trainingExperience: string | null; exerciseConfidence: string | null; recentTrainingBreak: string | null; initialTrainingLevel: string | null; trainingDaysPerWeek: number | null; availableWeekdays: number[] | null; preferredWeekdays: number[] | null; sessionDurationMin: number | null; sessionDurationIsPlus: boolean | null; sessionDurationRange: string | null; trainingLocation: string | null; otherLocationLabel: string | null; availableEquipment: string[] | null; otherEquipmentLabel: string | null; painOrLimitation: boolean | null; affectedBodyAreas: string[] | null; priorityMuscles: string[] | null; aerobicPracticeFrequency: string | null; aerobicSafetyLimitation: boolean | null; activities: TrainingActivity[] | null };
  nutrition: { mealsPerDay: number | null; mealScheduleFlexibility: string | null; foodPreparationStyle: string | null; foodBudgetStyle: string | null; availableMealMoments: string[] | null; foodPreparationAvailability: string | null; currentEatingRoutine: string | null; dietaryPattern: string | null; dietaryPatternOtherLabel: string | null; hasFoodRestrictions: boolean | null; usesSupplements: boolean | null; acceptsEggs: boolean | null; acceptsDairy: boolean | null; restrictions: NutritionRestriction[] | null; dislikedFoods: DeclaredFood[] | null; preferredFoods: DeclaredFood[] | null; supplements: Supplement[] | null };
};
export type LegacyFitnessContext = FitnessContextShape & { source: "v1"; payloadSchemaVersion: null };
export type V21FitnessContext = FitnessContextShape & { source: "v2_1"; onboardingVersion: 2; payloadSchemaVersion: 2 };
export type V22FitnessContext = FitnessContextShape & { source: "v2_2"; onboardingVersion: 2; payloadSchemaVersion: 3 };
export type UserFitnessContext = LegacyFitnessContext | V21FitnessContext | V22FitnessContext;

export type LegacyProfileRow = { nome: string | null; onboarding_version: number | null; onboarding_completed?: boolean | null; onboarding_completed_at?: string | null; objetivo: string | null; nivel_experiencia: string | null; dias_treino: number | null; idade: number | null; sexo: string | null; peso: number | null; altura: number | null };
export type CompletionReceiptRow = { onboarding_version: number; payload_schema_version: number; canonicalization_version: number; completed_at: string };
export type V2HealthRow = { birth_date: string; biological_sex: string; height_cm: number; weight_kg: number; target_weight_kg: number | null; primary_goal: string };

export type V21TrainingRow = { onboarding_payload_schema_version?: null; primary_goal: string; priority_muscles: string[]; training_experience: string; exercise_confidence: string; recent_training_break: string | null; initial_training_level: string; training_days_per_week: number; available_weekdays: number[]; preferred_weekdays?: null; session_duration_min: number; session_duration_is_plus: boolean; session_duration_range?: null; training_location: string; other_location_label: string | null; available_equipment: string[]; other_equipment_label: string | null; pain_or_limitation: boolean; affected_body_areas: string[]; aerobic_practice_frequency?: null; aerobic_safety_limitation?: null };
export type V22TrainingRow = { onboarding_payload_schema_version: 3; primary_goal: string; priority_muscles: null; training_experience: null; exercise_confidence: null; recent_training_break: null; initial_training_level: string; training_days_per_week: number; available_weekdays: null; preferred_weekdays: number[]; session_duration_min: null; session_duration_is_plus: null; session_duration_range: string; training_location: string; other_location_label: string | null; available_equipment: string[]; other_equipment_label: string | null; pain_or_limitation: null; affected_body_areas: null; aerobic_practice_frequency: string; aerobic_safety_limitation: boolean };
export type V21NutritionRow = { onboarding_payload_schema_version?: null; meals_per_day: number | null; meal_schedule_flexibility: string | null; food_preparation_style: string; food_budget_style: string; available_meal_moments?: null; food_preparation_availability?: null; current_eating_routine?: null; dietary_pattern: string; dietary_pattern_other_label: string | null; has_food_restrictions: boolean; uses_supplements: boolean; accepts_eggs: boolean | null; accepts_dairy: boolean | null };
export type V22NutritionRow = { onboarding_payload_schema_version: 3; meals_per_day: null; meal_schedule_flexibility: null; food_preparation_style: null; food_budget_style: null; available_meal_moments: string[]; food_preparation_availability: string; current_eating_routine: string; dietary_pattern: string; dietary_pattern_other_label: string | null; has_food_restrictions: boolean; uses_supplements: boolean; accepts_eggs: null; accepts_dairy: null };
type ActivityRow = { onboarding_payload_schema_version?: number | null; activity_code: string; other_activity_label: string | null; schedule_type: string | null; available_weekdays: number[] | null; sessions_per_week: number | null; duration_range?: string | null; intensity?: string | null };
type SharedRows = { health: V2HealthRow | null; activities?: ActivityRow[]; restrictions?: Array<{ restriction_type: string; restriction_code: string | null; declared_label: string }>; dislikedFoods?: Array<{ food_code: string | null; declared_label: string }>; preferredFoods?: Array<{ food_code: string | null; declared_label: string }>; supplements?: Array<{ supplement_code: string | null; declared_label: string }> };
export type V21ContextRows = SharedRows & { training: V21TrainingRow | null; nutrition: V21NutritionRow | null };
export type V22ContextRows = SharedRows & { training: V22TrainingRow | null; nutrition: V22NutritionRow | null };
export type V2ContextRows = V21ContextRows;

function record(value: unknown): Record<string, unknown> | null { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : null; }
function nullableString(value: unknown): boolean { return value === null || typeof value === "string"; }
function nullableNumber(value: unknown): boolean { return value === null || (typeof value === "number" && Number.isFinite(value)); }
function strings(value: unknown): value is string[] { return Array.isArray(value) && value.every((x) => typeof x === "string"); }
function weekdays(value: unknown, empty = true): value is number[] { return Array.isArray(value) && (empty || value.length > 0) && value.every((x) => Number.isInteger(x) && x >= 1 && x <= 7) && new Set(value).size === value.length; }
function allowed(value: unknown, values: readonly string[]): value is string { return typeof value === "string" && values.includes(value); }
function validLabel(value: unknown): value is string { return typeof value === "string" && value.trim().length > 0 && [...value].length <= 160 && !/[\u0000-\u001f\u007f-\u009f]/.test(value); }
function incomplete(paths: readonly string[]): never { throw new FitnessContextError("V2_INCOMPLETE", "O contexto V2 está incompleto ou incompatível.", paths); }

export function parseLegacyProfileRow(value: unknown): LegacyProfileRow {
  const v=record(value); if (!v) throw new FitnessContextError("READ_FAILED", "O perfil retornado é inválido.");
  if (!nullableString(v.nome) || !nullableNumber(v.onboarding_version) || (v.onboarding_completed !== undefined && v.onboarding_completed !== null && typeof v.onboarding_completed !== "boolean") || (v.onboarding_completed_at !== undefined && !nullableString(v.onboarding_completed_at)) || !nullableString(v.objetivo) || !nullableString(v.nivel_experiencia) || !nullableNumber(v.dias_treino) || !nullableNumber(v.idade) || !nullableString(v.sexo) || !nullableNumber(v.peso) || !nullableNumber(v.altura)) throw new FitnessContextError("READ_FAILED", "O perfil retornado contém tipos inválidos.");
  return v as LegacyProfileRow;
}

export function parseCompletionReceipt(value: unknown, profile: LegacyProfileRow): CompletionReceiptRow {
  const v=record(value);
  if (!v || v.onboarding_version !== 2 || typeof v.payload_schema_version !== "number" || typeof v.canonicalization_version !== "number" || typeof v.completed_at !== "string" || profile.onboarding_completed !== true || !profile.onboarding_completed_at || profile.onboarding_completed_at !== v.completed_at) throw new FitnessContextError("V2_RECEIPT_INVALID", "Não foi possível validar a conclusão do perfil V2.");
  if (v.payload_schema_version !== 2 && v.payload_schema_version !== 3) throw new FitnessContextError("UNSUPPORTED_SCHEMA", "A versão do perfil V2 não é suportada.");
  if (v.canonicalization_version !== v.payload_schema_version) throw new FitnessContextError("V2_RECEIPT_INVALID", "Não foi possível validar a versão do perfil V2.");
  return v as CompletionReceiptRow;
}

function parseBase(input: unknown): Record<string, unknown> {
  const v=record(input); if (!v) incomplete(["context"]);
  const h=record(v.health),t=record(v.training),n=record(v.nutrition); const bad:string[]=[];
  if(!h)bad.push("health");if(!t)bad.push("training");if(!n)bad.push("nutrition");
  if(bad.length)incomplete(bad);
  if(typeof h!.birth_date!=="string")bad.push("health.birth_date");if(typeof h!.biological_sex!=="string")bad.push("health.biological_sex");if(!nullableNumber(h!.height_cm)||h!.height_cm===null)bad.push("health.height_cm");if(!nullableNumber(h!.weight_kg)||h!.weight_kg===null)bad.push("health.weight_kg");if(!nullableNumber(h!.target_weight_kg))bad.push("health.target_weight_kg");if(typeof h!.primary_goal!=="string")bad.push("health.primary_goal");
  for(const key of ["activities","restrictions","dislikedFoods","preferredFoods","supplements"])if(!Array.isArray(v[key]))bad.push(key);
  if(bad.length)incomplete(bad);return v;
}
function validateCollections(v:Record<string,unknown>,schema:2|3):string[]{const bad:string[]=[];for(const x of v.activities as unknown[]){const a=record(x);if(!a||a.onboarding_payload_schema_version!==(schema===3?3:null)||typeof a.activity_code!=="string"||!nullableString(a.other_activity_label)||!nullableString(a.schedule_type)||(a.available_weekdays!==null&&!weekdays(a.available_weekdays,false))||!nullableNumber(a.sessions_per_week)||!nullableString(a.duration_range??null)||!nullableString(a.intensity??null)){bad.push("activities");break;}}const specs=[["restrictions",["restriction_type","declared_label"],["restriction_code"]],["dislikedFoods",["declared_label"],["food_code"]],["preferredFoods",["declared_label"],["food_code"]],["supplements",["declared_label"],["supplement_code"]]] as const;for(const [key,req,opt]of specs)if((v[key]as unknown[]).some(x=>{const r=record(x);return !r||req.some(k=>typeof r[k]!=="string")||opt.some(k=>!nullableString(r[k]));}))bad.push(key);return bad;}

export function parseV21ContextRows(input: unknown): V21ContextRows {
  const v=parseBase(input),t=record(v.training)!,n=record(v.nutrition)!,bad=validateCollections(v,2);
  for(const k of ["primary_goal","training_experience","exercise_confidence","initial_training_level","training_location"])if(typeof t[k]!=="string")bad.push(`training.${k}`);
  if((t.onboarding_payload_schema_version??null)!==null)bad.push("training.onboarding_payload_schema_version");for(const k of ["priority_muscles","available_equipment","affected_body_areas"])if(!strings(t[k]))bad.push(`training.${k}`);if(!weekdays(t.available_weekdays))bad.push("training.available_weekdays");if(!nullableNumber(t.training_days_per_week)||t.training_days_per_week===null)bad.push("training.training_days_per_week");if(!nullableNumber(t.session_duration_min)||t.session_duration_min===null)bad.push("training.session_duration_min");for(const k of ["session_duration_is_plus","pain_or_limitation"])if(typeof t[k]!=="boolean")bad.push(`training.${k}`);for(const k of ["preferred_weekdays","session_duration_range","aerobic_practice_frequency","aerobic_safety_limitation"])if((t[k]??null)!==null)bad.push(`training.${k}`);
  for(const k of ["food_preparation_style","food_budget_style","dietary_pattern"])if(typeof n[k]!=="string")bad.push(`nutrition.${k}`);if((n.onboarding_payload_schema_version??null)!==null)bad.push("nutrition.onboarding_payload_schema_version");for(const k of ["available_meal_moments","food_preparation_availability","current_eating_routine"])if((n[k]??null)!==null)bad.push(`nutrition.${k}`);for(const k of ["has_food_restrictions","uses_supplements"])if(typeof n[k]!=="boolean")bad.push(`nutrition.${k}`);if(!nullableNumber(n.meals_per_day))bad.push("nutrition.meals_per_day");for(const k of ["meal_schedule_flexibility","dietary_pattern_other_label"])if(!nullableString(n[k]))bad.push(`nutrition.${k}`);for(const k of ["accepts_eggs","accepts_dairy"])if(n[k]!==null&&typeof n[k]!=="boolean")bad.push(`nutrition.${k}`);
  if(bad.length)incomplete(bad);return v as unknown as V21ContextRows;
}
export const parseV2ContextRows=parseV21ContextRows;

const GOALS=["hypertrophy","fat_loss","conditioning"],LEVELS=["beginner","intermediate","advanced"],LOCATIONS=["full_gym","simple_gym","home","outdoor","other"],RANGES=["under_30","30_45","45_60","60_90","over_90"],AEROBIC=["never","sometimes","regularly"],MEALS=["breakfast","morning_snack","lunch","afternoon_snack","dinner","supper"];
export function parseV22ContextRows(input: unknown): V22ContextRows {
  const v=parseBase(input),h=record(v.health)!,t=record(v.training)!,n=record(v.nutrition)!,bad=validateCollections(v,3);
  if(!allowed(h.primary_goal,GOALS)||h.primary_goal!==t.primary_goal)bad.push("health.primary_goal");if(!allowed(h.biological_sex,["male","female","not_specified"]))bad.push("health.biological_sex");if((h.height_cm as number)<=0||(h.height_cm as number)>300)bad.push("health.height_cm");if((h.weight_kg as number)<=0||(h.weight_kg as number)>500)bad.push("health.weight_kg");if(h.target_weight_kg!==null)bad.push("health.target_weight_kg");
  if(t.onboarding_payload_schema_version!==3)bad.push("training.onboarding_payload_schema_version");if(!allowed(t.primary_goal,GOALS))bad.push("training.primary_goal");if(!allowed(t.initial_training_level,LEVELS))bad.push("training.initial_training_level");if(![2,3,4,5,6].includes(t.training_days_per_week as number))bad.push("training.training_days_per_week");if(!weekdays(t.preferred_weekdays))bad.push("training.preferred_weekdays");if(!allowed(t.session_duration_range,RANGES))bad.push("training.session_duration_range");if(!allowed(t.training_location,LOCATIONS))bad.push("training.training_location");if(!nullableString(t.other_location_label)||(t.training_location==="other")!==(t.other_location_label!==null)||(t.other_location_label!==null&&!validLabel(t.other_location_label)))bad.push("training.other_location_label");if(!strings(t.available_equipment)||new Set(t.available_equipment as string[]).size!==(t.available_equipment as string[])?.length||(t.available_equipment as string[])?.some(x=>!["bodyweight","dumbbells","barbell","weight_plates","bench","rack","cable_machine","selectorized_machines","smith_machine","leg_press","resistance_bands","pull_up_bar","kettlebell","other"].includes(x)))bad.push("training.available_equipment");if(!nullableString(t.other_equipment_label)||((t.available_equipment as string[])?.includes("other")??false)!==(t.other_equipment_label!==null)||(t.other_equipment_label!==null&&!validLabel(t.other_equipment_label)))bad.push("training.other_equipment_label");if(t.training_location==="full_gym"&&((t.available_equipment as unknown[])?.length!==0||t.other_equipment_label!==null))bad.push("training.available_equipment");if(t.training_location!=="full_gym"&&(t.available_equipment as unknown[])?.length===0)bad.push("training.available_equipment");if(!allowed(t.aerobic_practice_frequency,AEROBIC))bad.push("training.aerobic_practice_frequency");if(typeof t.aerobic_safety_limitation!=="boolean")bad.push("training.aerobic_safety_limitation");for(const k of ["priority_muscles","training_experience","exercise_confidence","recent_training_break","available_weekdays","session_duration_min","session_duration_is_plus","pain_or_limitation","affected_body_areas"])if(t[k]!==null)bad.push(`training.${k}`);
  for(const raw of v.activities as unknown[]){const a=record(raw)!;if(!allowed(a.activity_code,["running","football","cycling","combat_sports","swimming","walking","other"])||!nullableString(a.other_activity_label)||(a.activity_code==="other")!==(a.other_activity_label!==null)||(a.other_activity_label!==null&&!validLabel(a.other_activity_label))||a.schedule_type!==null||(a.duration_range!==null&&!allowed(a.duration_range,RANGES))||(a.intensity!==null&&!allowed(a.intensity,["low","moderate","high"]))||(a.sessions_per_week!==null&&(!Number.isInteger(a.sessions_per_week)||(a.sessions_per_week as number)<=0)))bad.push("activities");}if(new Set((v.activities as Array<Record<string,unknown>>).map(a=>a.activity_code)).size!==(v.activities as unknown[]).length)bad.push("activities");
  if(n.onboarding_payload_schema_version!==3)bad.push("nutrition.onboarding_payload_schema_version");if(!strings(n.available_meal_moments)||!(n.available_meal_moments as string[]).length||new Set(n.available_meal_moments as string[]).size!==(n.available_meal_moments as string[]).length||(n.available_meal_moments as string[]).some(x=>!MEALS.includes(x)))bad.push("nutrition.available_meal_moments");if(!allowed(n.food_preparation_availability,["limited","moderate","flexible"]))bad.push("nutrition.food_preparation_availability");if(!allowed(n.current_eating_routine,["structured","variable","irregular"]))bad.push("nutrition.current_eating_routine");if(!allowed(n.dietary_pattern,["omnivore","vegetarian","vegan","pescatarian","other"])||!nullableString(n.dietary_pattern_other_label)||(n.dietary_pattern==="other")!==(n.dietary_pattern_other_label!==null)||(n.dietary_pattern_other_label!==null&&!validLabel(n.dietary_pattern_other_label)))bad.push("nutrition.dietary_pattern");for(const k of ["has_food_restrictions","uses_supplements"])if(typeof n[k]!=="boolean")bad.push(`nutrition.${k}`);for(const k of ["meals_per_day","meal_schedule_flexibility","food_preparation_style","food_budget_style","accepts_eggs","accepts_dairy"])if(n[k]!==null)bad.push(`nutrition.${k}`);
  const restrictions=v.restrictions as Array<Record<string,unknown>>,foods=[...(v.dislikedFoods as Array<Record<string,unknown>>),...(v.preferredFoods as Array<Record<string,unknown>>)],supplements=v.supplements as Array<Record<string,unknown>>;
  if(restrictions.some(x=>!allowed(x.restriction_type,["allergy","intolerance","dietary_restriction","other"])||(x.restriction_code!==null&&!allowed(x.restriction_code,["lactose","gluten","milk","egg","peanut","tree_nuts","soy","fish","shellfish"]))||!validLabel(x.declared_label))||Boolean(n.has_food_restrictions)!==(restrictions.length>0))bad.push("restrictions");
  if(foods.some(x=>x.food_code!==null||!validLabel(x.declared_label)))bad.push("foods");
  if(supplements.some(x=>(x.supplement_code!==null&&!allowed(x.supplement_code,["whey_protein","creatine","mass_gainer","protein_powder_other","multivitamin"]))||!validLabel(x.declared_label))||Boolean(n.uses_supplements)!==(supplements.length>0))bad.push("supplements");
  if(bad.length)incomplete([...new Set(bad)]);return v as unknown as V22ContextRows;
}

export function calculateAge(birthDate:string,today=new Date()):number{const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(birthDate);if(!m)incomplete(["health.birth_date"]);const y=Number(m![1]),mo=Number(m![2]),d=Number(m![3]),date=new Date(Date.UTC(y,mo-1,d));if(date.getUTCFullYear()!==y||date.getUTCMonth()+1!==mo||date.getUTCDate()!==d||date>today)incomplete(["health.birth_date"]);let age=today.getUTCFullYear()-y;if(today.getUTCMonth()+1<mo||(today.getUTCMonth()+1===mo&&today.getUTCDate()<d))age--;if(age<18)incomplete(["health.birth_date"]);return age;}
const emptyNutrition={mealsPerDay:null,mealScheduleFlexibility:null,foodPreparationStyle:null,foodBudgetStyle:null,availableMealMoments:null,foodPreparationAvailability:null,currentEatingRoutine:null,dietaryPattern:null,dietaryPatternOtherLabel:null,hasFoodRestrictions:null,usesSupplements:null,acceptsEggs:null,acceptsDairy:null,restrictions:null,dislikedFoods:null,preferredFoods:null,supplements:null} as const;
export function buildLegacyFitnessContext(p:LegacyProfileRow):LegacyFitnessContext{return{source:"v1",onboardingVersion:p.onboarding_version,payloadSchemaVersion:null,identity:{name:p.nome},health:{primaryGoal:p.objetivo,birthDate:null,age:p.idade,biologicalSex:p.sexo,heightCm:p.altura,weightKg:p.peso,targetWeightKg:null},training:{primaryGoal:p.objetivo,trainingExperience:p.nivel_experiencia,exerciseConfidence:null,recentTrainingBreak:null,initialTrainingLevel:null,trainingDaysPerWeek:p.dias_treino,availableWeekdays:null,preferredWeekdays:null,sessionDurationMin:null,sessionDurationIsPlus:null,sessionDurationRange:null,trainingLocation:null,otherLocationLabel:null,availableEquipment:null,otherEquipmentLabel:null,painOrLimitation:null,affectedBodyAreas:null,priorityMuscles:null,aerobicPracticeFrequency:null,aerobicSafetyLimitation:null,activities:null},nutrition:{...emptyNutrition}};}
function collections(r:SharedRows){return{restrictions:(r.restrictions??[]).map(x=>({restrictionType:x.restriction_type,restrictionCode:x.restriction_code,declaredLabel:x.declared_label})),dislikedFoods:(r.dislikedFoods??[]).map(x=>({foodCode:x.food_code,declaredLabel:x.declared_label})),preferredFoods:(r.preferredFoods??[]).map(x=>({foodCode:x.food_code,declaredLabel:x.declared_label})),supplements:(r.supplements??[]).map(x=>({supplementCode:x.supplement_code,declaredLabel:x.declared_label}))};}
function activities(r:SharedRows):TrainingActivity[]{return(r.activities??[]).map(x=>({activityCode:x.activity_code,otherActivityLabel:x.other_activity_label,scheduleType:x.schedule_type,availableWeekdays:x.available_weekdays,sessionsPerWeek:x.sessions_per_week,durationRange:x.duration_range??null,intensity:x.intensity??null}));}
export function buildV21FitnessContext(p:LegacyProfileRow,r:V21ContextRows,today?:Date):V21FitnessContext{if(!r.health||!r.training||!r.nutrition)incomplete(["health","training","nutrition"]);const h=r.health,t=r.training,n=r.nutrition;return{source:"v2_1",onboardingVersion:2,payloadSchemaVersion:2,identity:{name:p.nome},health:{primaryGoal:h.primary_goal,birthDate:h.birth_date,age:calculateAge(h.birth_date,today),biologicalSex:h.biological_sex,heightCm:h.height_cm,weightKg:h.weight_kg,targetWeightKg:h.target_weight_kg},training:{primaryGoal:t.primary_goal,trainingExperience:t.training_experience,exerciseConfidence:t.exercise_confidence,recentTrainingBreak:t.recent_training_break,initialTrainingLevel:t.initial_training_level,trainingDaysPerWeek:t.training_days_per_week,availableWeekdays:t.available_weekdays,preferredWeekdays:null,sessionDurationMin:t.session_duration_min,sessionDurationIsPlus:t.session_duration_is_plus,sessionDurationRange:null,trainingLocation:t.training_location,otherLocationLabel:t.other_location_label,availableEquipment:t.available_equipment,otherEquipmentLabel:t.other_equipment_label,painOrLimitation:t.pain_or_limitation,affectedBodyAreas:t.affected_body_areas,priorityMuscles:t.priority_muscles,aerobicPracticeFrequency:null,aerobicSafetyLimitation:null,activities:activities(r)},nutrition:{mealsPerDay:n.meals_per_day,mealScheduleFlexibility:n.meal_schedule_flexibility,foodPreparationStyle:n.food_preparation_style,foodBudgetStyle:n.food_budget_style,availableMealMoments:null,foodPreparationAvailability:null,currentEatingRoutine:null,dietaryPattern:n.dietary_pattern,dietaryPatternOtherLabel:n.dietary_pattern_other_label,hasFoodRestrictions:n.has_food_restrictions,usesSupplements:n.uses_supplements,acceptsEggs:n.accepts_eggs,acceptsDairy:n.accepts_dairy,...collections(r)}};}
export const buildV2FitnessContext=buildV21FitnessContext;
export function buildV22FitnessContext(p:LegacyProfileRow,r:V22ContextRows,today?:Date):V22FitnessContext{if(!r.health||!r.training||!r.nutrition)incomplete(["health","training","nutrition"]);const h=r.health,t=r.training,n=r.nutrition;return{source:"v2_2",onboardingVersion:2,payloadSchemaVersion:3,identity:{name:p.nome},health:{primaryGoal:h.primary_goal,birthDate:h.birth_date,age:calculateAge(h.birth_date,today),biologicalSex:h.biological_sex,heightCm:h.height_cm,weightKg:h.weight_kg,targetWeightKg:null},training:{primaryGoal:t.primary_goal,trainingExperience:null,exerciseConfidence:null,recentTrainingBreak:null,initialTrainingLevel:t.initial_training_level,trainingDaysPerWeek:t.training_days_per_week,availableWeekdays:null,preferredWeekdays:t.preferred_weekdays,sessionDurationMin:null,sessionDurationIsPlus:null,sessionDurationRange:t.session_duration_range,trainingLocation:t.training_location,otherLocationLabel:t.other_location_label,availableEquipment:t.available_equipment,otherEquipmentLabel:t.other_equipment_label,painOrLimitation:null,affectedBodyAreas:null,priorityMuscles:null,aerobicPracticeFrequency:t.aerobic_practice_frequency,aerobicSafetyLimitation:t.aerobic_safety_limitation,activities:activities(r)},nutrition:{mealsPerDay:null,mealScheduleFlexibility:null,foodPreparationStyle:null,foodBudgetStyle:null,availableMealMoments:n.available_meal_moments,foodPreparationAvailability:n.food_preparation_availability,currentEatingRoutine:n.current_eating_routine,dietaryPattern:n.dietary_pattern,dietaryPatternOtherLabel:n.dietary_pattern_other_label,hasFoodRestrictions:n.has_food_restrictions,usesSupplements:n.uses_supplements,acceptsEggs:null,acceptsDairy:null,...collections(r)}};}
